# Generated by Django 5.0.2 on 2026-08-09 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_user_ownership_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiactivity',
            new_name='scanner_aia_user_id_8fdf15_idx',
            old_name='scanner_aia_user_id_5b38e1_idx',
        ),
        migrations.RenameIndex(
            model_name='fileanalysis',
            new_name='scanner_fil_user_id_e9d363_idx',
            old_name='scanner_fil_user_id_9f8d67_idx',
        ),
        migrations.RenameIndex(
            model_name='incident',
            new_name='scanner_inc_user_id_fa7418_idx',
            old_name='scanner_inc_user_id_6a5f78_idx',
        ),
        migrations.RenameIndex(
            model_name='incident',
            new_name='scanner_inc_status_597067_idx',
            old_name='scanner_inc_status_b13d29_idx',
        ),
        migrations.RenameIndex(
            model_name='incident',
            new_name='scanner_inc_severit_7a46a4_idx',
            old_name='scanner_inc_severit_8172df_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='scanner_rep_user_id_0396a7_idx',
            old_name='scanner_rep_user_id_c683b5_idx',
        ),
        migrations.RenameIndex(
            model_name='scanresult',
            new_name='scanner_sca_user_id_2bd5eb_idx',
            old_name='scanner_sca_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='scanresult',
            new_name='scanner_sca_domain_62db39_idx',
            old_name='scanner_sca_domain_idx',
        ),
        migrations.RenameIndex(
            model_name='scanresult',
            new_name='scanner_sca_risk_le_b4a5a1_idx',
            old_name='scanner_sca_risk_le_521021_idx',
        ),
        migrations.RenameIndex(
            model_name='threatintelresult',
            new_name='scanner_thr_user_id_7bd887_idx',
            old_name='scanner_thr_user_id_10795c_idx',
        ),
        migrations.RenameIndex(
            model_name='threatintelresult',
            new_name='scanner_thr_severit_2af4b9_idx',
            old_name='scanner_thr_severit_3ff03e_idx',
        ),
    ]
