# Generated by Django 5.0.2 on 2026-08-13 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_rename_scanner_aia_user_id_5b38e1_idx_scanner_aia_user_id_8fdf15_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='threatintelresult',
            name='confidence',
            field=models.IntegerField(default=0, help_text='0-100 evidence confidence percentage'),
        ),
        migrations.AddField(
            model_name='threatintelresult',
            name='detection_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='threatintelresult',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threatintelresult',
            name='harmless_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='threatintelresult',
            name='malicious_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='threatintelresult',
            name='normalized_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='threatintelresult',
            name='provider',
            field=models.CharField(default='Multi-Provider', max_length=100),
        ),
        migrations.AddField(
            model_name='threatintelresult',
            name='query_type',
            field=models.CharField(default='REPUTATION', max_length=50),
        ),
        migrations.AddField(
            model_name='threatintelresult',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('RATE_LIMITED', 'Rate Limited'), ('UNAUTHORIZED', 'Unauthorized'), ('NOT_FOUND', 'Not Found'), ('TIMEOUT', 'Timeout'), ('ERROR', 'Error'), ('PARTIAL_SUCCESS', 'Partial Success'), ('NOT_APPLICABLE', 'Not Applicable')], default='SUCCESS', max_length=50),
        ),
        migrations.AddField(
            model_name='threatintelresult',
            name='suspicious_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='threatintelresult',
            name='target_type',
            field=models.CharField(choices=[('DOMAIN', 'Domain'), ('URL', 'URL'), ('IP', 'IP Address'), ('FILE_HASH', 'File Hash')], default='DOMAIN', max_length=50),
        ),
        migrations.AddField(
            model_name='threatintelresult',
            name='threat_score',
            field=models.IntegerField(default=0, help_text='0-100 deterministic risk score'),
        ),
        migrations.AddField(
            model_name='threatintelresult',
            name='undetected_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='threatintelresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='threatintelresult',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20),
        ),
        migrations.AlterField(
            model_name='threatintelresult',
            name='threat_type',
            field=models.CharField(default='REPUTATION', max_length=100),
        ),
        migrations.AddIndex(
            model_name='threatintelresult',
            index=models.Index(fields=['target'], name='scanner_thr_target_0838ea_idx'),
        ),
        migrations.AddIndex(
            model_name='threatintelresult',
            index=models.Index(fields=['target_type'], name='scanner_thr_target__551f23_idx'),
        ),
        migrations.AddIndex(
            model_name='threatintelresult',
            index=models.Index(fields=['provider'], name='scanner_thr_provide_471afd_idx'),
        ),
        migrations.AddIndex(
            model_name='threatintelresult',
            index=models.Index(fields=['status'], name='scanner_thr_status_7af614_idx'),
        ),
    ]
