# Generated by Django 5.0.2 on 2026-08-13 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_threatintelresult_confidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanalysis',
            name='analysis_status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('ANALYZING', 'Analyzing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='COMPLETED', max_length=30),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='confidence',
            field=models.IntegerField(default=0, help_text='0-100 evidence confidence percentage'),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='detected_type',
            field=models.CharField(choices=[('PE', 'Windows Executable'), ('ELF', 'Linux Executable'), ('SCRIPT', 'Script File'), ('DOCUMENT', 'Document File'), ('ARCHIVE', 'Archive File'), ('MOBILE', 'Mobile Package'), ('GENERIC', 'Generic Binary')], default='GENERIC', max_length=50),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='entropy',
            field=models.FloatField(default=0.0, help_text='Shannon entropy (0.0 to 8.0)'),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='entropy_category',
            field=models.CharField(default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='extension',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='md5',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='mime_type',
            field=models.CharField(default='application/octet-stream', max_length=100),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='normalized_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='original_filename',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='sha1',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='signature_status',
            field=models.CharField(default='NOT_PRESENT', max_length=30),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='stored_filename',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='threat_score',
            field=models.IntegerField(default=0, help_text='0-100 deterministic threat score'),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='virustotal_detections',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='virustotal_status',
            field=models.CharField(default='NOT_FOUND', max_length=30),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='yara_matches',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='yara_status',
            field=models.CharField(default='NO_MATCH', max_length=30),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='file_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='file_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='risk_level',
            field=models.CharField(default='low', max_length=20),
        ),
        migrations.AddIndex(
            model_name='fileanalysis',
            index=models.Index(fields=['sha256'], name='scanner_fil_sha256_3b102a_idx'),
        ),
        migrations.AddIndex(
            model_name='fileanalysis',
            index=models.Index(fields=['detected_type'], name='scanner_fil_detecte_6e2988_idx'),
        ),
        migrations.AddIndex(
            model_name='fileanalysis',
            index=models.Index(fields=['severity'], name='scanner_fil_severit_05f481_idx'),
        ),
        migrations.AddIndex(
            model_name='fileanalysis',
            index=models.Index(fields=['analysis_status'], name='scanner_fil_analysi_dd7dab_idx'),
        ),
    ]
