# Generated by Django 6.0.1 on 2026-08-18 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_fileanalysis_analysis_status_fileanalysis_confidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSLScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=512)),
                ('domain', models.CharField(max_length=512)),
                ('port', models.IntegerField(default=443)),
                ('certificate_status', models.CharField(choices=[('VALID', 'Valid'), ('EXPIRING_SOON', 'Expiring Soon'), ('EXPIRED', 'Expired'), ('NOT_YET_VALID', 'Not Yet Valid'), ('HOSTNAME_MISMATCH', 'Hostname Mismatch'), ('INVALID', 'Invalid'), ('UNAVAILABLE', 'Unavailable')], default='VALID', max_length=50)),
                ('issuer_cn', models.CharField(blank=True, default='', max_length=255)),
                ('subject_cn', models.CharField(blank=True, default='', max_length=255)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('days_remaining', models.IntegerField(blank=True, null=True)),
                ('tls_version', models.CharField(default='UNKNOWN', max_length=50)),
                ('cipher_name', models.CharField(default='UNKNOWN', max_length=100)),
                ('cipher_bits', models.IntegerField(default=0)),
                ('hostname_valid', models.BooleanField(default=True)),
                ('san_list', models.JSONField(blank=True, default=list)),
                ('security_issues', models.JSONField(blank=True, default=list)),
                ('threat_score', models.IntegerField(default=0, help_text='0-100 deterministic risk score')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('confidence', models.IntegerField(default=90)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('TIMEOUT', 'Timeout'), ('SSRF_BLOCKED', 'SSRF Blocked'), ('INVALID_INPUT', 'Invalid Input')], default='SUCCESS', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('structured_evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ssl_scans', to='scanner.scanresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='scanner_ssl_user_id_d45d65_idx'), models.Index(fields=['domain'], name='scanner_ssl_domain_6f1967_idx'), models.Index(fields=['severity'], name='scanner_ssl_severit_c4d47e_idx'), models.Index(fields=['status'], name='scanner_ssl_status_cdb804_idx'), models.Index(fields=['certificate_status'], name='scanner_ssl_certifi_81b033_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhoisLookupResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=512)),
                ('registrar', models.CharField(default='NOT_AVAILABLE', max_length=255)),
                ('registry_domain_id', models.CharField(default='NOT_AVAILABLE', max_length=255)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('expires_date', models.DateTimeField(blank=True, null=True)),
                ('domain_age_days', models.IntegerField(blank=True, null=True)),
                ('days_until_expiration', models.IntegerField(blank=True, null=True)),
                ('age_category', models.CharField(default='UNKNOWN', max_length=30)),
                ('expiration_category', models.CharField(default='UNKNOWN', max_length=30)),
                ('nameservers', models.JSONField(blank=True, default=list)),
                ('domain_status', models.JSONField(blank=True, default=list)),
                ('registrant_org', models.CharField(default='NOT_AVAILABLE', max_length=255)),
                ('registrant_country', models.CharField(default='NOT_AVAILABLE', max_length=100)),
                ('dnssec', models.CharField(default='UNSIGNED', max_length=30)),
                ('security_indicators', models.JSONField(blank=True, default=list)),
                ('threat_score', models.IntegerField(default=0, help_text='0-100 deterministic risk score')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('confidence', models.IntegerField(default=85)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('NOT_FOUND', 'Not Found'), ('TIMEOUT', 'Timeout'), ('ERROR', 'Error'), ('SSRF_BLOCKED', 'SSRF Blocked'), ('NOT_APPLICABLE', 'Not Applicable'), ('INVALID_INPUT', 'Invalid Input')], default='SUCCESS', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('structured_evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whois_lookups', to='scanner.scanresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whois_lookups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='scanner_who_user_id_1a4818_idx'), models.Index(fields=['domain'], name='scanner_who_domain_f69daa_idx'), models.Index(fields=['severity'], name='scanner_who_severit_8700dd_idx'), models.Index(fields=['status'], name='scanner_who_status_40a173_idx'), models.Index(fields=['age_category'], name='scanner_who_age_cat_f382c2_idx')],
            },
        ),
    ]
