# Generated by Django 6.0.1 on 2026-08-18 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_sslscanresult_whoislookupresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URLScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=2048)),
                ('normalized_url', models.CharField(max_length=2048)),
                ('final_url', models.CharField(blank=True, default='', max_length=2048)),
                ('hostname', models.CharField(max_length=512)),
                ('domain', models.CharField(max_length=512)),
                ('scheme', models.CharField(default='https', max_length=20)),
                ('port', models.IntegerField(default=443)),
                ('primary_ip', models.CharField(blank=True, default='', max_length=100)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, default='', max_length=150)),
                ('server', models.CharField(blank=True, default='', max_length=150)),
                ('redirect_count', models.IntegerField(default=0)),
                ('redirect_chain', models.JSONField(blank=True, default=list)),
                ('ssl_result', models.JSONField(blank=True, default=dict)),
                ('whois_result', models.JSONField(blank=True, default=dict)),
                ('threat_intel_result', models.JSONField(blank=True, default=dict)),
                ('indicators', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('threat_score', models.IntegerField(default=0, help_text='0-100 deterministic risk score')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('confidence', models.IntegerField(default=80)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('TIMEOUT', 'Timeout'), ('TLS_ERROR', 'TLS Error'), ('CONNECTION_REFUSED', 'Connection Refused'), ('REDIRECT_ERROR', 'Redirect Error'), ('REDIRECT_LOOP', 'Redirect Loop'), ('SSRF_BLOCKED', 'SSRF Blocked'), ('INVALID_INPUT', 'Invalid Input')], default='SUCCESS', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('structured_evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_scans', to='scanner.scanresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='scanner_url_user_id_33d55b_idx'), models.Index(fields=['domain'], name='scanner_url_domain_0bed89_idx'), models.Index(fields=['severity'], name='scanner_url_severit_c841c4_idx'), models.Index(fields=['status'], name='scanner_url_status_2c3cb2_idx'), models.Index(fields=['http_status'], name='scanner_url_http_st_ad4276_idx')],
            },
        ),
    ]
