# Generated by Django 6.0.1 on 2026-08-18 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_urlscanresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=512)),
                ('target_type', models.CharField(default='HOSTNAME', max_length=50)),
                ('resolved_ips', models.JSONField(blank=True, default=list)),
                ('primary_ip', models.CharField(blank=True, default='', max_length=100)),
                ('scan_profile', models.CharField(default='COMMON', max_length=50)),
                ('requested_ports', models.JSONField(blank=True, default=list)),
                ('results', models.JSONField(blank=True, default=list)),
                ('open_ports', models.JSONField(blank=True, default=list)),
                ('closed_ports', models.JSONField(blank=True, default=list)),
                ('filtered_ports', models.JSONField(blank=True, default=list)),
                ('indicators', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('threat_score', models.IntegerField(default=0, help_text='0-100 deterministic risk score')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('confidence', models.IntegerField(default=85)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('TIMEOUT', 'Timeout'), ('DNS_ERROR', 'DNS Error'), ('SSRF_BLOCKED', 'SSRF Blocked'), ('INVALID_INPUT', 'Invalid Input')], default='SUCCESS', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('structured_evidence', models.JSONField(blank=True, default=dict)),
                ('scan_duration', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='port_scans', to='scanner.scanresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='scanner_por_user_id_f055be_idx'), models.Index(fields=['target'], name='scanner_por_target_253152_idx'), models.Index(fields=['severity'], name='scanner_por_severit_88c1c5_idx'), models.Index(fields=['status'], name='scanner_por_status_1f3545_idx'), models.Index(fields=['scan_profile'], name='scanner_por_scan_pr_7abbd0_idx')],
            },
        ),
    ]
