# Generated by Django 6.0.1 on 2026-08-18 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_portscanresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOCAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('analysis_type', models.CharField(default='COMPOSITE', max_length=50)),
                ('target_identifiers', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.IntegerField(default=0, help_text='0-100 deterministic combined risk score')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('confidence', models.IntegerField(default=75)),
                ('threat_level', models.CharField(choices=[('LOW', 'Low Threat'), ('MEDIUM', 'Medium Threat'), ('HIGH', 'High Threat'), ('CRITICAL', 'Critical Threat'), ('REVIEW_REQUIRED', 'Review Required')], default='LOW', max_length=30)),
                ('summary', models.TextField(blank=True, default='')),
                ('findings', models.JSONField(blank=True, default=list)),
                ('correlations', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('evidence_sources', models.JSONField(blank=True, default=list)),
                ('source_records', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ANALYZING', 'Analyzing'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='COMPLETED', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('analysis_duration', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soc_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='scanner_soc_user_id_cfc13d_idx'), models.Index(fields=['target'], name='scanner_soc_target_2214cb_idx'), models.Index(fields=['severity'], name='scanner_soc_severit_0e076f_idx'), models.Index(fields=['threat_level'], name='scanner_soc_threat__659890_idx'), models.Index(fields=['status'], name='scanner_soc_status_6d292c_idx')],
            },
        ),
    ]
