# Generated by Django 5.0.2 on 2026-08-22 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_socanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=512)),
                ('analysis_mode', models.CharField(default='SECURITY_ASSESSMENT', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('FAILED_AI', 'AI Unavailable (Fallback)')], default='PENDING', max_length=50)),
                ('risk_score', models.IntegerField(default=0, help_text='0-100 deterministic risk score from SOC Engine')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('confidence', models.IntegerField(default=0)),
                ('threat_level', models.CharField(default='LOW', max_length=30)),
                ('summary', models.TextField(blank=True, default='')),
                ('findings', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('evidence_sources', models.JSONField(blank=True, default=list)),
                ('tools_used', models.JSONField(blank=True, default=list)),
                ('steps_completed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soc_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessions', to='scanner.socanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(default=1)),
                ('action', models.CharField(default='EVALUATE', max_length=50)),
                ('tool_name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='COMPLETED', max_length=50)),
                ('reasoning_summary', models.TextField(blank=True, default='')),
                ('input_summary', models.JSONField(blank=True, default=dict)),
                ('output_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='scanner.agentsession')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='AgentToolExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='SUCCESS', max_length=50)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='scanner.agentsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['user', '-created_at'], name='scanner_age_user_id_a2579f_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['target'], name='scanner_age_target_8670c7_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['status'], name='scanner_age_status_35cecc_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['severity'], name='scanner_age_severit_095654_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstep',
            index=models.Index(fields=['session', 'step_number'], name='scanner_age_session_82da96_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttoolexecution',
            index=models.Index(fields=['session', '-created_at'], name='scanner_age_session_93fd72_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttoolexecution',
            index=models.Index(fields=['tool_name'], name='scanner_age_tool_na_d95043_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttoolexecution',
            index=models.Index(fields=['status'], name='scanner_age_status_29f0f8_idx'),
        ),
    ]
