# Generated by Django 5.0.2 on 2026-08-22 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0010_agentsession_agentstep_agenttoolexecution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('target', models.CharField(db_index=True, max_length=512)),
                ('title', models.CharField(default='CyberGuardian Security Assessment Report', max_length=255)),
                ('report_type', models.CharField(choices=[('COMPREHENSIVE', 'Comprehensive Security Assessment'), ('SOC_ASSESSMENT', 'SOC Security Assessment'), ('AI_SECURITY_ASSESSMENT', 'AI-Assisted Security Assessment'), ('MODULE_SPECIFIC', 'Module-Specific Assessment')], default='COMPREHENSIVE', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial (Available Sources)'), ('FAILED', 'Failed')], default='COMPLETED', max_length=30)),
                ('risk_score', models.IntegerField(default=0)),
                ('severity', models.CharField(default='LOW', max_length=20)),
                ('confidence', models.IntegerField(default=0)),
                ('threat_level', models.CharField(default='LOW', max_length=20)),
                ('summary', models.TextField(blank=True, default='')),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='scanner.agentsession')),
                ('soc_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='scanner.socanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='scanner_sec_user_id_8c14e8_idx'), models.Index(fields=['target', '-created_at'], name='scanner_sec_target_eec91b_idx'), models.Index(fields=['status'], name='scanner_sec_status_5dda04_idx'), models.Index(fields=['severity'], name='scanner_sec_severit_cf0fef_idx'), models.Index(fields=['report_type'], name='scanner_sec_report__217824_idx')],
            },
        ),
    ]
