# Generated by Django 5.0.2 on 2026-09-10 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0011_securityreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('target', models.CharField(db_index=True, max_length=512)),
                ('recipient_name', models.CharField(max_length=255)),
                ('certificate_type', models.CharField(choices=[('CYBERSECURITY_ANALYSIS_COMPLETION', 'Cybersecurity Analysis Completion Certificate')], default='CYBERSECURITY_ANALYSIS_COMPLETION', max_length=64)),
                ('title', models.CharField(default='CyberGuardian AI Cybersecurity Analysis Completion Certificate', max_length=255)),
                ('issue_date', models.DateField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], db_index=True, default='VALID', max_length=20)),
                ('verification_token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('verification_url', models.CharField(blank=True, max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdf/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='scanner.securityreport')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_certificates', to=settings.AUTH_USER_MODEL)),
                ('soc_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='scanner.socanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_id', models.CharField(db_index=True, max_length=64)),
                ('assessment_id', models.CharField(blank=True, default='', max_length=128)),
                ('event_type', models.CharField(choices=[('CERTIFICATE_ELIGIBILITY_CHECKED', 'Certificate Eligibility Checked'), ('CERTIFICATE_GENERATION_STARTED', 'Certificate Generation Started'), ('CERTIFICATE_GENERATED', 'Certificate Generated'), ('CERTIFICATE_GENERATION_FAILED', 'Certificate Generation Failed'), ('CERTIFICATE_VIEWED', 'Certificate Viewed'), ('CERTIFICATE_DOWNLOADED', 'Certificate Downloaded'), ('CERTIFICATE_VERIFIED', 'Certificate Verified'), ('CERTIFICATE_REVOKED', 'Certificate Revoked')], db_index=True, max_length=50)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('PUBLIC', 'Public Visitor'), ('SYSTEM', 'System Process')], default='USER', max_length=20)),
                ('status', models.CharField(default='SUCCESS', max_length=30)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('endpoint', models.CharField(blank=True, default='', max_length=255)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='scanner.certificate')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_id'], name='scanner_cer_certifi_6d1805_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['user', '-created_at'], name='scanner_cer_user_id_dbdb89_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['status'], name='scanner_cer_status_564d55_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['verification_token'], name='scanner_cer_verific_2babf6_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['issue_date'], name='scanner_cer_issue_d_6348c5_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['target'], name='scanner_cer_target_facecd_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateauditlog',
            index=models.Index(fields=['cert_id', '-timestamp'], name='scanner_cer_cert_id_47aece_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateauditlog',
            index=models.Index(fields=['event_type', '-timestamp'], name='scanner_cer_event_t_43d437_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateauditlog',
            index=models.Index(fields=['actor', '-timestamp'], name='scanner_cer_actor_i_a80283_idx'),
        ),
        migrations.AddIndex(
            model_name='certificateauditlog',
            index=models.Index(fields=['timestamp'], name='scanner_cer_timesta_b202a7_idx'),
        ),
    ]
