# Generated by Django 5.0.2 on 2026-09-10 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0012_certificate_certificateauditlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='assessment_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='certificate',
            name='assessment_type',
            field=models.CharField(db_index=True, default='SECURITY_ASSESSMENT', max_length=64),
        ),
        migrations.AddField(
            model_name='certificate',
            name='file_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='scanner.fileanalysis'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='port_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='scanner.portscanresult'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='result_status',
            field=models.CharField(db_index=True, default='SAFE', max_length=50),
        ),
        migrations.AddField(
            model_name='certificate',
            name='risk_level',
            field=models.CharField(db_index=True, default='NO_RISK', max_length=50),
        ),
        migrations.AddField(
            model_name='certificate',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='scan_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='scanner.scanresult'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='ssl_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='scanner.sslscanresult'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='threat_intel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='scanner.threatintelresult'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='url_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='scanner.urlscanresult'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='whois_lookup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='scanner.whoislookupresult'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['assessment_type'], name='scanner_cer_assessm_54ebfe_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['assessment_id'], name='scanner_cer_assessm_111c02_idx'),
        ),
    ]
