# Generated by Django 6.0.1 on 2026-09-28 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0013_certificate_assessment_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(choices=[('DROP', 'Drop / Block'), ('ACCEPT', 'Accept / Allow'), ('REJECT', 'Reject')], default='DROP', max_length=20)),
                ('reason', models.CharField(default='Multiple failed login attempts detected on internal firewall', max_length=255)),
                ('rule_direction', models.CharField(default='INGRESS', max_length=20)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewall_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='scanner_fir_user_id_84d1fc_idx'), models.Index(fields=['ip_address'], name='scanner_fir_ip_addr_debf23_idx'), models.Index(fields=['status'], name='scanner_fir_status_c16a03_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_id', models.CharField(db_index=True, max_length=128)),
                ('action_type', models.CharField(max_length=64)),
                ('status', models.CharField(default='RESOLVED', max_length=30)),
                ('target', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'recommendation_id'], name='scanner_rec_user_id_43c8f0_idx'), models.Index(fields=['user', 'action_type'], name='scanner_rec_user_id_24dfda_idx')],
            },
        ),
    ]
