# Generated by Django 5.0.2 on 2026-08-09 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification_adminauditlog'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='adminauditlog',
                    new_name='users_admin_admin_i_94a534_idx',
                    old_name='users_admin_admin_i_c009d1_idx',
                ),
                migrations.RenameIndex(
                    model_name='adminauditlog',
                    new_name='users_admin_target__11a7cc_idx',
                    old_name='users_admin_target__132e01_idx',
                ),
                migrations.RenameIndex(
                    model_name='notification',
                    new_name='users_notif_user_id_f3f50a_idx',
                    old_name='users_notif_user_id_44f33d_idx',
                ),
                migrations.AddField(
                    model_name='user',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='user',
                    name='role',
                    field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('SOC_ANALYST', 'SOC Analyst'), ('SUPER_ADMIN', 'Super Admin')], default='USER', max_length=20),
                ),
                migrations.AddField(
                    model_name='user',
                    name='status',
                    field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=15),
                ),
                migrations.AddField(
                    model_name='user',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True),
                ),
            ],
            database_operations=[]
        ),
    ]
